/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.controle.FilaBancaria;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas.flor
 */
public class JFGeradorSenha extends javax.swing.JFrame {

    static ArrayList<String> lstSenha = new ArrayList<>();
    static Senha senha = new Senha();
    
    /**
     * Creates new form JFGeradorSenha
     */
    public JFGeradorSenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnTpSenhaC = new javax.swing.JButton();
        btnTpSenhaR = new javax.swing.JButton();
        btnTpSenhaP = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        idSuaSenha = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnCx1 = new javax.swing.JButton();
        btnCx2 = new javax.swing.JButton();
        btnCx3 = new javax.swing.JButton();
        btnCx4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idChamadaSenha = new javax.swing.JTextField();
        idChamadaCaixa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.white));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Escolha seu tipo de atendimento");

        btnTpSenhaC.setText("Comum");
        btnTpSenhaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTpSenhaCActionPerformed(evt);
            }
        });

        btnTpSenhaR.setText("Rápido");
        btnTpSenhaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTpSenhaRActionPerformed(evt);
            }
        });

        btnTpSenhaP.setText("Prioritário");
        btnTpSenhaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTpSenhaPActionPerformed(evt);
            }
        });

        jLabel6.setText("Sua senha é:");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        idSuaSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idSuaSenha.setBorder(null);
        idSuaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idSuaSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(idSuaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(idSuaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTpSenhaC)
                        .addGap(18, 18, 18)
                        .addComponent(btnTpSenhaR)
                        .addGap(18, 18, 18)
                        .addComponent(btnTpSenhaP))
                    .addComponent(jLabel6))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTpSenhaC)
                    .addComponent(btnTpSenhaR)
                    .addComponent(btnTpSenhaP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.white));

        btnCx1.setText("Caixa 1");
        btnCx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCx1ActionPerformed(evt);
            }
        });

        btnCx2.setText("Caixa 2");
        btnCx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCx2ActionPerformed(evt);
            }
        });

        btnCx3.setText("Caixa 3");
        btnCx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCx3ActionPerformed(evt);
            }
        });

        btnCx4.setText("Caixa 4");
        btnCx4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCx4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCx1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCx2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCx3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCx4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCx1)
                    .addComponent(btnCx2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCx3)
                    .addComponent(btnCx4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Para clientes:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Para caixas:");

        idChamadaSenha.setEditable(false);
        idChamadaSenha.setBackground(new java.awt.Color(255, 255, 255));
        idChamadaSenha.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        idChamadaSenha.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        idChamadaCaixa.setEditable(false);
        idChamadaCaixa.setBackground(new java.awt.Color(255, 255, 255));
        idChamadaCaixa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        idChamadaCaixa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idChamadaCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idChamadaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(207, 207, 207))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idChamadaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idChamadaCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTpSenhaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTpSenhaCActionPerformed
        // TODO add your handling code here:
        gerarSenha("C");
        idSuaSenha.setText(senha.getSenha());
    }//GEN-LAST:event_btnTpSenhaCActionPerformed

    private void btnTpSenhaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTpSenhaRActionPerformed
        // TODO add your handling code here:
        gerarSenha("R");
        idSuaSenha.setText(senha.getSenha());
    }//GEN-LAST:event_btnTpSenhaRActionPerformed

    private void btnTpSenhaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTpSenhaPActionPerformed
        // TODO add your handling code here:
        gerarSenha("P");
        idSuaSenha.setText(senha.getSenha());
    }//GEN-LAST:event_btnTpSenhaPActionPerformed

    private void idSuaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idSuaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idSuaSenhaActionPerformed

    private void gerarSenha(String tipoAtendimento){
        senha.createSenha(tipoAtendimento);
        lstSenha.add(senha.getSenha());
    }
    
    public void informaAtendimentoSenha (String senha, String caixa){
        idChamadaSenha.setText(senha);
        idChamadaCaixa.setText(caixa);
    }
    
    private boolean chamadaAtendimento(String caixaAtendimento, String tipoAtendimento){
        String senhaPriorizada = "";
        boolean statusRetorno = false;
        
        for(String priorizaSenha : lstSenha){
            if(priorizaSenha.contains(tipoAtendimento)){
                senhaPriorizada = priorizaSenha;
                statusRetorno = true;
                break;
            }
        }
        
        if(statusRetorno){
            lstSenha.remove(senhaPriorizada);
            informaAtendimentoSenha(senhaPriorizada, caixaAtendimento);
            return true;
        }else{
            return false;
        }
    }
    
    private void btnCx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCx1ActionPerformed
        // TODO add your handling code here:
        // Prioriza Preferencial
        if (!chamadaAtendimento("Caixa 1", "P")){
            if(!chamadaAtendimento("Caixa 1", "R")){
                chamadaAtendimento("Caixa 1", "C");
            }
        }
                
    }//GEN-LAST:event_btnCx1ActionPerformed

    private void btnCx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCx2ActionPerformed
        // TODO add your handling code here:
        // Prioriza Rapido
        if(!chamadaAtendimento("Caixa 2", "R")){
            if(!chamadaAtendimento("Caixa 2", "P")){
                chamadaAtendimento("Caixa 2", "C");
            }
        }
    }//GEN-LAST:event_btnCx2ActionPerformed

    private void btnCx3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCx3ActionPerformed
        // TODO add your handling code here:
        // Prioriza Rapido
        if(!chamadaAtendimento("Caixa 3", "R")){
            if(!chamadaAtendimento("Caixa 3", "P")){
                chamadaAtendimento("Caixa 3", "C");
            }
        }
    }//GEN-LAST:event_btnCx3ActionPerformed

    private void btnCx4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCx4ActionPerformed
        // TODO add your handling code here:
        // Prioriza Comum
        if(!chamadaAtendimento("Caixa 4", "C")){
            if(!chamadaAtendimento("Caixa 4", "P")){
                chamadaAtendimento("Caixa 4", "R");
            }
        }
    }//GEN-LAST:event_btnCx4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFGeradorSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFGeradorSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFGeradorSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFGeradorSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFGeradorSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCx1;
    private javax.swing.JButton btnCx2;
    private javax.swing.JButton btnCx3;
    private javax.swing.JButton btnCx4;
    private javax.swing.JButton btnTpSenhaC;
    private javax.swing.JButton btnTpSenhaP;
    private javax.swing.JButton btnTpSenhaR;
    private javax.swing.JTextField idChamadaCaixa;
    private javax.swing.JTextField idChamadaSenha;
    private javax.swing.JTextField idSuaSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
